services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend         # build context is the folder itself
    ports:
      - "3000:3000"
    depends_on:
      - backend
