services:
  - type: web
    name: ai-on-fhir-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: PYTHONPATH      
        value: /app
      - key: PORT
        value: 8000

  # ──────────────── Next.js frontend ───────────────
  - type: web
    name: ai-on-fhir-frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile  # Dockerfile already runs `npm run start`
    dockerContext: frontend
    autoDeploy: true
    envVars:
      # ⚠️ swap this to the actual backend URL after the first backend deploy
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-on-fhir-backend.onrender.com
      - key: PORT
        value: 3000
